config/routes.rb
Pages::Application.routes.draw do

  match '/home' => 'pages#home', :as => :home
  match '/contact' => 'pages#contact', :as => :contact
  match '/fun' => 'pages#fun', :as => :fun
  match '/who' => 'pages#who', :as => :who

  scope "/admin" do
    resources :pages do
      resources :comments
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :message
  belongs_to :page
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @page = Page.find_by_id(params[:page_id])
    if @page
      @comments = @page.comments
    end
    #@comments = Comment.all
    #@comments = []
    #@comments ||= @page.comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @page = Page.find_by_id(params[:page_id])
    @comment = Comment.new
    #@comment = @page.build_comment

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @page = Page.find_by_id(params[:page_id])
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @page = Page.find_by_id(params[:page_id])
    @comment = Comment.new(params[:comment])
    @comment.page = @page

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :page_comments, notice: 'Comment was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @page = Page.find_by_id(params[:page_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to page_comments_path(@page) }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  # Public stuff

  def home # Page id=1
    @page = Page.find_by_id(1)

    display_or_404(@page)
  end

  def contact # Page id=2
    @page = Page.find_by_id(2)

    display_or_404(@page)
  end

  def fun # Page id=3
    @page = Page.find_by_id(3)

    display_or_404(@page)
  end

  def who # Page id=4
    @page = Page.find_by_id(4)

    display_or_404(@page)
  end

  private

  def display_or_404(page)
    if page.nil?
      redirect_to "/404"
    else
      respond_to do |format|
        format.html # home.html.erb
        format.json { render json: page }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_for [@page, @comment], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :message, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :message, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                :page_comments, :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%- model_class = @comment.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<h1>Comments for page <%= @page.title %></h1>

<div class="row">
  <div class="span4">
    <p>This page has <%= @comments.count %> comments.</p>

    <%= link_to "Post a new comment", :new_page_comment, :class => "btn btn-success" %>
    <%= link_to "This url", page_comments_url(@page) %>
  </div>
  <div class="span8">
    <% @comments.each do |comment| %>
      <div class="comment">
        <p><%= comment.message %></p>
        <p><%= link_to "Moar", page_comment_path(@page, comment) %></p>
        <p><%= link_to "Edit", edit_page_comment_path(@page, comment) %></p>
        <p><%= link_to "Destroy", page_comment_path(@page, comment), :method => :delete %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<%- model_class = @comment.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/comments/old-index.html.erb
<h1>Comments for page: <%= @page.title %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment %></td>
        <td><%= comment.message %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_page_comment(comment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      page_comment(comment),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_page_comment,
            :class => 'btn btn-primary' %>

app/views/comments/show.html.erb
<h1>comments#show</h1>

<div class="row">
  <div class="span4">
    <p><b>Comment message</b></p>
    <p><%= @comment.message %></p>
  </div>
  <div class="span4">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pages</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Pages</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "home", :home %></li>
            <li><%= link_to "contact", :contact %></li>
            <li><%= link_to "fun", :fun %></li>
            <li><%= link_to "who", :who %></li>
            <li><%= link_to "admin pages", :pages %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/pages/contact.html.erb
<h1><%= @page.title %></h1>

<div class="row">
  <div class="span4">
    <%= @page.content %>
  </div>
  <div class="span8">
    <p>Static stuff</p>
  </div>
</div>

app/views/pages/edit.html.erb
<%- model_class = @page.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/pages/home.html.erb
<h2><%= @page.title %></h2>
<div class="row">
  <div class="span6">
    <p>Left stuff</p>
  </div>

  <div class="span6">
    <p><%= @page.content %></p>
  </div>
</div>

<h3>On a related note...</h3>

<div class="row">
  <div class="span3">
    <p>One fourth</p>
  </div>
</div>

app/views/pages/index.html.erb
<%- model_class = Page.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.id, page_path(page) %></td>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%=l page.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_page_path(page), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      page_path(page),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_page_path,
            :class => 'btn btn-primary' %>

app/views/pages/new.html.erb
<%- model_class = @page.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/pages/show.html.erb
<%- model_class = @page.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:title) %>:</strong><br>
  <%= @page.title %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:content) %>:</strong><br>
  <%= @page.content %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_page_path(@page), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              page_path(@page),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>